  version: '3.8'
  services:
    falco:
      restart: always
      container_name: falco
      image: registry.cn-hangzhou.aliyuncs.com/goodmangll/falco:stable
      volumes:
        - ./config:/user/src/app/config # 配置文件
        - ./logs:/user/src/app/logs # 日志文件
        - ./nginx/logs/:/usr/local/openresty/nginx/logs # nginx日志文件
      ports:
        - 8095:80
        - 13000：13000  