version: '3.3'

services:
  # nginx 劫持
  emby2Alist:
    image: nginx:alpine
    container_name: emby2Alist
    ports:
      - 8095:80
    volumes:
      - ./emby2Alist/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./emby2Alist/nginx/conf.d:/etc/nginx/conf.d
      - ./emby2Alist/nginx/embyCache:/var/cache/nginx/emby
    restart: always
  # 直连代理
  fileRawUrlProxy:
    restart: always
    container_name: fileRawUrlProxy
    image: registry.cn-hangzhou.aliyuncs.com/goodmangll/filerawurlproxy:1.0.0
    volumes:
      - ./fileRawUrlProxy/config:/app/config
      - ./fileRawUrlProxy/logs:/app/logs
    ports:
      - "13000:13000"