version: '3.8'
services:
  falco:
    restart: always
    container_name: falco
    image: registry.cn-hangzhou.aliyuncs.com/goodmangll/falco:stable
    volumes:
      - ./config:/user/src/app/config # 配置文件
      - ./logs:/user/src/app/logs # 日志文件
      # - ./nginx/conf/:/etc/nginx/ # 配置文件
      # - ./nginx/cert/:/etc/cert/ # ssl证书
      # - ./nginx/html/:/usr/share/nginx/html/ # 默认显示的index网页
      # - ./nginx/logs/:/var/log/nginx/ # nginx日志文件
    ports:
      - "8095:80"
      